version: "3.3"

services:
  postgres:
    image: postgres:13
    environment:
      - POSTGRES_DB=
      - POSTGRES_USER=yisus
      - POSTGRES_PASSWORD=lolitoxd28
    ports:
      - 5432:5432
    volumes:
      - ./postgres_data:/var/lib/postgresql/data